version: "3"
services:
  # Jaeger(Trace Viewer)
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.50.0
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "16686:16686" # web GUI
      - "14317:4317" # for directly debugging from otel client
      - "14318:4318" # for directly debugging from otel client

  # Zipkin(Trace Viewer)
  zipkin:
    image: openzipkin/zipkin:2.24
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9411:9411" # web GUI

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:0.88.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/:/data/
    ports:
      - "1888:1888" # pprof extension (for web GUI)
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension (for http)
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "55679:55679" # zpages extension (for web GUI)
    depends_on:
      - jaeger-all-in-one
      - zipkin

  prometheus:
    image: prom/prometheus:v2.47.2
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9090:9090"
