receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  debug:
    verbosity: detailed

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
    tls:
      insecure: true

  # gRPC
  otlp:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  file:
    path: /data/dump.json

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin, otlp, file]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus, file]
